import path from 'node:path';
import express from 'express';
import { StaticRouter } from 'react-router';
import { DataCache } from '../app/lib/data/data-cache.ts';
import { DataContext } from '../app/lib/data/data-context.ts';
import { createDataInjector } from './lib/data-injector.ts';
import { StreamingSSRRenderer } from './lib/streaming-ssr-renderer.ts';
import { Root } from './components/root.tsx';
import { readManifest } from './lib/manifest.ts';

const app = express();
const port = process.env.PORT ?? 3007;

// Static handler
app.use(express.static(path.resolve(import.meta.dirname, '../../public')));

// Express 5 (path-to-regexp v8) no longer accepts a bare '*'
app.get('/{*splat}', (req, res, next) => {
    // Paths with an extension are static
    if (path.extname(req.path)) {
        return next();
    }

    // Needs to be generated by esbuild at first
    const manifest = readManifest();

    // A new one per request, so users never share data
    const dataCache = new DataCache();

    const renderer = new StreamingSSRRenderer({
        // ESM entry: dynamic import() of lazy chunks needs type="module"
        bootstrapModules: [manifest.entry.js],

        onShellReady: () => {
            res.statusCode = 200;
            res.setHeader('Content-Type', 'text/html; charset=utf-8');
            console.log('Shell ready - All without suspense', req.url);
        },

        onAllReady: () => {
            console.log('All Suspenses Resolved', req.url);
        },

        onError: () => {
            res.statusCode = 500;
        },

        // Data loaded during render goes into the stream as <script> tags
        injectHTML: createDataInjector(dataCache),

        timeout: 10_000,
    });

    // The router only provides context, so it wraps Root from the outside:
    // StaticRouter here, BrowserRouter in src/client/index.tsx, Root is shared.
    // originalUrl keeps the query, BrowserRouter reads the same URL on hydration
    const stream = renderer.renderToStream(
        <DataContext value={dataCache}>
            <StaticRouter location={req.originalUrl}>
                <Root manifest={manifest} />
            </StaticRouter>
        </DataContext>,
    );

    stream.pipe(res);
});

app.listen(port, (err) => {
    if (err) {
        throw err;
    }
    
    console.log(`Streaming SSR app listening on port ${port}`);
});
